# 模型配置
model:
  base_model_path: "/mnt/tags-friend2/model"
  model_path: "/mnt/tags-friend2/model/llama3.2-vision-11b"
  device_map: "auto"
  torch_dtype: "bfloat16"
  trust_remote_code: true

# 图像处理配置
image:
  max_new_tokens: 1024
  num_beams: 1
  do_sample: true
  temperature: 0.2
  top_p: 0.8
  repetition_penalty: 1.1

# Gradio界面配置
gradio:
  share: false
  inbrowser: true
  server_name: "0.0.0.0"
  server_port: 7860
  debug: false

# 系统配置
system:
  no_reload: true  # gr.NO_RELOAD 的值 